### ISSUE TITLE
The model isn't loading

### ISSUE THREAD

**Issue by RezowanTalukder** [ccoreilly/vosk-browser#1]
I see there is an model.tar.gz in public folder in react example. I want to use it for testing purposes, but the model isn't loading. 

![image](https://user-images.githubusercontent.com/35560302/112484625-4d8a6300-8da4-11eb-80ff-a84383094175.png)

**Comment by ccoreilly** [comment]
Hi!

I guess you cloned the repository and have started the react example with npm start? The react example expects the models to be in `public/models` but they have not been pushed to the repository in the master branch. The `model.tar.gz` is not used by the example (I should remove it). You can find all the models in the gh-pages branch, just place them in `public/models` and it should work.

Here are the models:
https://github.com/ccoreilly/vosk-browser/tree/gh-pages/models

**Comment by RezowanTalukder** [comment]
Thank you so much. You are so helpful. #respect

**Comment by ccoreilly** [comment]
Yes, this is an issue that only happens in chrome with the demo (it has nothing to do with the vosk-browser library). On Firefox it does not complain. I started working on a fix but I haven't fully tested it, I'll try to push it later today.

**Comment by RezowanTalukder** [comment]
Yes its working fine in Firefox but the problem is my model has pretty good accuracy for audio directly through mic but when I upload audio file(.mp3 or .flac) of same transcripts it can't recognize the word properly. where is the issue can you guess anything ?

**Comment by ccoreilly** [comment]
I would assume loss of quality during conversion? The library does no conversio, the trick is that the demo reads the audio stream being played by the browser in a hidden audio tag.

Have you tried with a 16kHz wav (which is what most models expect)?

**Comment by RezowanTalukder** [comment]
I just check with 16khz .flac audio, it can't recognise words properly.

**Comment by RezowanTalukder** [comment]
I see the file upload part doesn't work on your demo as well for English model. Have you checked it ?

**Comment by RezowanTalukder** [comment]
Your demo is working for English  .mp3 file very well. but my model works fine if I play audio in speaker but it doesn't transcribe well while uploading same audio file. No idea where's the wrong here in my model.

**Comment by ccoreilly** [comment]
Hi @RezowanTalukder ! 

Just to understand it better, you have issues with file transcription when using another English model than the one used in the demo, am I right? Could you maybe share the model? Is it also a wideband (16kHz) model?

**Comment by RezowanTalukder** [comment]
yes, basically I am using a model of Bangla language. The problem is its work very nice when i speak through mic. but when i upload and Bangla audio file it can't recognize any word.

I have used googles open SLR bangla dataset and I have sent you the model in email.

**Comment by RezowanTalukder** [comment]
bangla_model.tar.gz
<https://drive.google.com/file/d/1OfFkq3Vb_jbr_Da1zfipYun6cVHP0GRq/view?usp=drive_web>

**Comment by RezowanTalukder** [comment]
...
