### ISSUE TITLE
Attribution difficult

### ISSUE THREAD

**Issue by Yahweasel** [ccoreilly/vosk-browser#12]
The NOTICES file doesn't include all dependent software, but every piece of dependent software requires attribution. This makes it extremely difficult for anyone to put together a correct (and legally mandatory) attribution and license notice. I put this one together, which I believe includes all dependencies: https://raw.githubusercontent.com/Yahweasel/ennuicastr/master/src/vosk-browser-license.js .

Moreover, I was surprised to find GSL in the mix. GSL is under the GPL (_not_ the LGPL), so if it's being used, then vosk-browser as a whole is licensed under the GPL. That's no problem for my use, but it should be documented somewhere. Weirdly, though, as far as I can tell, it's _not_ actually using GSL. The kaldi patch seems to add GSL to the configure, but doesn't add any uses of GSL as far as I can tell. If it was some experiment (perhaps from the original porter of vosk?) it should just be removed, to fix this licensing snafu.

**Comment by ccoreilly** [comment]
Thanks for the support and heads up. GSL is actually used but I didn't check the licensing. I will try to compile ATLAS to WASM as a more license friendly alternative.

Thanks for the updated NOTICE, I'll push the changes.

**Comment by nshmyrev** [comment]
> GSL is actually used but I didn't check the licensing. I will try to compile ATLAS to WASM as a more license friendly alternative

Not clear why are you looking for Atlas. openblas-clapack which is default in Vosk should work just fine.

**Comment by ccoreilly** [comment]
Thanks @nshmyrev, I just realized my mistake and was looking into the `extras/install_openblas_clapack.sh` in order to get openblas compiled to wasm.

**Comment by ccoreilly** [comment]
I resolved the dependency and published a new version with the updated attribution. Thanks again @Yahweasel
