### ISSUE TITLE
run project,prompt :"You can run npm install --save worker_threads"

### ISSUE THREAD

**Issue by lcpCode** [ccoreilly/vosk-browser#14]
please help me,
use vosk-browser   prompt error：

Module not found: Can't resolve imported dependency "worker_threads"
Did you forget to install it? You can run: npm install --save worker_threads

 App •  WARNING  • Compilation succeeded but there are warning(s). Please check the log above.

**Comment by ccoreilly** [comment]
You can ignore that warning, it is specific to react when using some browser features.
