### ISSUE TITLE
model folder problem, and code modifications

### ISSUE THREAD

**Issue by awaisnaz** [ccoreilly/vosk-browser#2]
Hi.

While running the code at https://github.com/ccoreilly/vosk-browser/tree/gh-pages using Firefox and local server, the index.html file would not run. I inspected the source code, and the relative path of model given was "vosk-browser\models\vosk-model-small-en-us-0.15.tar.gz", which I corrected to "models\vosk-model-small-en-us-0.15.tar.gz".

I corrected the code in index.html, and the code ran, and generated Speech-to-text through given audio file (Direct audio through mic still didn't worked, though mic worked, but all it did was sending audio chunks and never display the results in the textarea).

If I need to modify the code, I am unable to do that. How do I modify it. Can you provide the source code?

thanks.

**Comment by ccoreilly** [comment]
The code in the gh-pages branch is the build result of the react code found here https://github.com/ccoreilly/vosk-browser/tree/master/examples/react
