### ISSUE TITLE
Adding Malayalam model to demo website

### ISSUE THREAD

**Issue by kavyamanohar** [ccoreilly/vosk-browser#20]
I have trained Malayalam ASR model for vosk and is available [here](https://gitlab.com/kavyamanohar/vosk-malayalam). Can this be added to the [demo website](https://ccoreilly.github.io/vosk-browser/)? Is there a way I can help?

**Comment by ccoreilly** [comment]
Thank you Kavya, I merged your pull request (I forgot to explain about some other things that needed updating and could not do it until now).

Can you test it? The model loads and something is written out, but I can't assess recognition quality.

I hope the attribution is correct, let me know if I should change anything.

**Comment by kavyamanohar** [comment]
@ccoreilly Thanks a lot for adding Malayalam model.

The recognition quality is as expected, considering the entire training was on read speech. Finally happy to see my model recognizing on the browser. 

The attribution is right. Thanks.
