### ISSUE TITLE
Recognizer not ready, ignoring (Browser testing)

### ISSUE THREAD

**Issue by Kolumor** [ccoreilly/vosk-browser#24]
Hello team!

I am testing your software using apache2 on a virtual machine running a Ubuntu server on windows.
This is the index and I was trying to test the microphone input.
2
1
3 <script type="application/javascript" src="https://cdn.jsdelivr.net/npm/vosk-browser@0.0.5/dist/vosk.js"></script>
1
2
3
4
5 <script>
6 async function init() {
7 const model = await Vosk.createModel('https://ccoreilly.github.io/vosk-browser/models/vosk-model-small-en-us-0.15.tar.gz');
8
9 const recognizer = new model.KaldiRecognizer();
10 recognizer.on("result", (message) => {
11 console.log(Result: ${message.result.text});
12 });
13 recognizer.on("partialresult", (message) => {
14 console.log(Partial result: ${message.result.partial});
15 });
16
17 const mediaStream = await navigator.mediaDevices.getUserMedia({
18 video: false,
19 audio: {
20 echoCancellation: true,
21 noiseSuppression: true,
22 channelCount: 1,
23 sampleRate: 16000
24 },
25 });
26
27 const audioContext = new AudioContext();
28 const recognizerNode = audioContext.createScriptProcessor(4096, 1, 1)
29 recognizerNode.onaudioprocess = (event) => {
30 try {
31 recognizer.acceptWaveform(event.inputBuffer)
32 } catch (error) {
33 console.error('acceptWaveform failed', error)
34 }
35 }
36 const source = audioContext.createMediaStreamSource(mediaStream);
37 source.connect(recognizerNode);
38 }
39
40 window.onload = init;
41 </script>
42
43
44 Hola!
45
46
~

The result on console is the repetition of the following lines:

Recognizer (id: d6562c55-8db5-4918-9c65-fc0d1f061ff2): Sending audioChunk vosk.js:333:29
Recognizer (id: d6562c55-8db5-4918-9c65-fc0d1f061ff2): process audio chunk with sampleRate 192000 94bb588b-5609-4bb8-bd34-b6f9f1c4968e:269:25
Recognizer (id: d6562c55-8db5-4918-9c65-fc0d1f061ff2): process audio chunk with sampleRate 192000 94bb588b-5609-4bb8-bd34-b6f9f1c4968e:269:25
Recognizer not ready, ignoring 94bb588b-5609-4bb8-bd34-b6f9f1c4968e:271:29
Recognizer not ready, ignoring 94bb588b-5609-4bb8-bd34-b6f9f1c4968e:271:29
Recognizer (id: d6562c55-8db5-4918-9c65-fc0d1f061ff2): Sending audioChunk vosk.js:333:29
Recognizer (id: d6562c55-8db5-4918-9c65-fc0d1f061ff2): process audio chunk with sampleRate 192000 94bb588b-5609-4bb8-bd34-b6f9f1c4968e:269:25
Recognizer not ready, ignoring 94bb588b-5609-4bb8-bd34-b6f9f1c4968e:271:29
Recognizer not ready, ignoring 94bb588b-5609-4bb8-bd34-b6f9f1c4968e:271:29

Could you please help me?
Thanks in advance

**Comment by ccoreilly** [comment]
Service workers have a strict CORS policy which means you need to serve the model from the same domain via https, otherwise the browser will not allow downloading the model.

**Comment by Kolumor** [comment]
I understand, but we don´t think that is the problem since the model loads correctly and the browser even asks permission to use the mic, which also only works on secure networks. Right?
I tested on Opera, Chrome, and Mozilla. 

This is what the Mozilla console shows:
![imagen_2021-12-03_112544](https://user-images.githubusercontent.com/91611178/144618598-a6fec11f-22c9-4556-8a18-3361a9669296.png)

This is the Opera browser:
![imagen_2021-12-03_112643](https://user-images.githubusercontent.com/91611178/144618744-86ad321d-1861-484c-8aed-ad4a5ccb5f7c.png)

And finally chrome: 
![imagen_2021-12-03_112801](https://user-images.githubusercontent.com/91611178/144618951-29b4a492-e983-49c0-9cfa-48f036582d88.png)

Thank you very much for your time.

**Comment by ccoreilly** [comment]
Oh, I see. You have to pass a string with the sampleRate to the recognizer constructor `model.KaldirRecognizer("16000")`

I guess I need to update the docs or examples.
