### ISSUE TITLE
Supported browsers

### ISSUE THREAD

**Issue by wizVR-zhangjun** [ccoreilly/vosk-browser#25]
Demo address The display browser supports Firefox. Is there any way to make it work at Microsoft edge  @ccoreilly

**Comment by ccoreilly** [comment]
Sure, the library works in all modern browsers, also MS Edge. The demo doesn't but check this other example which should work.
https://github.com/ccoreilly/vosk-browser/tree/master/examples/modern-vanilla

**Comment by ccoreilly** [comment]
And you need a vosk model named `model.tar.gz` at the same path (next to index.html). You can get them from the official vosk models page.
