### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by wizVR-zhangjun** [ccoreilly/vosk-browser#26]
examples Demo how does is work， Please give me some advice ，thank you

**Comment by ccoreilly** [comment]
Please be more specific. You can check the code of the demo in the examples folder of the repository.

**Comment by wizVR-zhangjun** [comment]
> 请更具体。您可以在存储库的示例文件夹中查看演示的代码。

The demo code did not run successfully

**Comment by wizVR-zhangjun** [comment]
> 请更具体。您可以在存储库的示例文件夹中查看演示的代码。

![image](https://user-images.githubusercontent.com/60952586/146698855-27948b0a-0503-484e-9259-68895f32825c.png)
Running this example directly reports an error. Thank you for your advice on how to run it.

**Comment by ccoreilly** [comment]
@wizVR-zhangjun you need to serve those files from a local http server, it will not work if you simply open `index.html` by double-clicking. Check [this page](https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/set_up_a_local_testing_server#%E8%BF%90%E8%A1%8C%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E6%9C%AC%E5%9C%B0_http_%E6%9C%8D%E5%8A%A1%E5%99%A8), hopefully it helps.

**Comment by wizVR-zhangjun** [comment]
> @wizVR-zhangjun你需要从本地 http 服务器提供这些文件，如果你只是`index.html`双击打开它是行不通的。检查[此页面](https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/set_up_a_local_testing_server#%E8%BF%90%E8%A1%8C%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E6%9C%AC%E5%9C%B0_http_%E6%9C%8D%E5%8A%A1%E5%99%A8)，希望它有所帮助。

**Comment by wizVR-zhangjun** [comment]
> @wizVR-zhangjun you need to serve those files from a local http server, it will not work if you simply open `index.html` by double-clicking. Check [this page](https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/set_up_a_local_testing_server#%E8%BF%90%E8%A1%8C%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E6%9C%AC%E5%9C%B0_http_%E6%9C%8D%E5%8A%A1%E5%99%A8), hopefully it helps.

@ccoreilly  I built an HTTPS service using Tomcat 
![image](https://user-images.githubusercontent.com/60952586/147018453-18af3c25-3621-443c-a7ec-2da6ba0f7a72.png)
Teacher, what's the problem

**Comment by wizVR-zhangjun** [comment]
> @wizVR-zhangjun you need to serve those files from a local http server, it will not work if you simply open `index.html` by double-clicking. Check [this page](https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/set_up_a_local_testing_server#%E8%BF%90%E8%A1%8C%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E6%9C%AC%E5%9C%B0_http_%E6%9C%8D%E5%8A%A1%E5%99%A8), hopefully it helps.

![image](https://user-images.githubusercontent.com/60952586/147044501-7a18e3c0-1457-4b99-9ff8-5c2f9485a355.png)

I don't know what caused this error， Please advise

**Comment by ccoreilly** [comment]
It is hard to know with the information you provided but the example expects to be at the root of the server. Select the modern-vanilla folder as the one that should be served by tomcat.

**Comment by ccoreilly** [comment]
And you need a vosk model named `model.tar.gz` at the same path (next to index.html). You can get them from the official vosk models page.

**Comment by wizVR-zhangjun** [comment]
> And you need a vosk model named `model.tar.gz` at the same path (next to index.html). You can get them from the official vosk models page.

Thank you for your help. According to your suggestion, I can successfully run the example here. Thank you again for your enthusiastic help

**Comment by wizVR-zhangjun** [comment]
> And you need a vosk model named `model.tar.gz` at the same path (next to index.html). You can get them from the official vosk models page.

I chose a Chinese model, but how does it recognize English? Can you help me out
