### ISSUE TITLE
npm i vosk-browser  report errors

### ISSUE THREAD

**Issue by wizVR-zhangjun** [ccoreilly/vosk-browser#27]
When I execute npm run dev 
![image](https://user-images.githubusercontent.com/60952586/147066637-f5d53ea2-553b-46e2-9339-f6442411a5fe.png)
Can you tell me the answer？

**Comment by wizVR-zhangjun** [comment]
We use web worker architecture, which does not support worker_ Threads, if not supported, is there any other way to save     @ccoreilly

**Comment by ccoreilly** [comment]
This is just a warning thrown by node, you can ignore it

**Comment by wizVR-zhangjun** [comment]
> This is just a warning thrown by node, you can ignore it

Thank you for your reply and relieve my doubts
