### ISSUE TITLE
hololens2 errors

### ISSUE THREAD

**Issue by wizVR-zhangjun** [ccoreilly/vosk-browser#28]
This example runs could not start audio source in hololens 
![image](https://user-images.githubusercontent.com/60952586/147312670-75570ff6-5a1a-4786-8d19-d33bfe15c354.png)

**Comment by ccoreilly** [comment]
I have no experience with hololens and cannot help, sorry.

**Comment by wizVR-zhangjun** [comment]
> I have no experience with hololens and cannot help, sorry.
The microphone can be accessed in holons, but the recognition rate is almost zero. Does this consume a lot of CPU ，Is there any other solution that can make the performance card less? Thank you

**Comment by ccoreilly** [comment]
@wizVR-zhangjun did you have any success?
