### ISSUE TITLE
Module not found: Error: Can't resolve 'worker_threads' in

### ISSUE THREAD

**Issue by tab-zero** [ccoreilly/vosk-browser#29]
I used the vosk-browser in one of my webpack projects and it throws these errors.
Module not found: Error: Can't resolve 'worker_threads' in ....

Steps I followed:
- npm run rollup
- and then in the lib npm pack .
- copied it to my webpack project and did a webpack start.

**Comment by tab-zero** [comment]
I also required to NodePolyfills plugin for webpack to work. 
https://github.com/webpack/webpack/pull/8460/commits/a68426e9255edcce7822480b78416837617ab065

**Comment by TrofinSorin** [comment]
I tried the react example and i get worker_threads error also.

**Comment by ccoreilly** [comment]
The latest commit will remove this warning. This library only targets the browser and worker_threads is only necessary in node, so it could be ignored.
