### ISSUE TITLE
Is the model downloaded or loaded on the browser side??

### ISSUE THREAD

**Issue by kavehcs** [ccoreilly/vosk-browser#3]
Hello and have a good time

Is the model downloaded or loaded on the browser side??

In the firefox browser, when I am loading the model, the models are downloaded and remain in the loading mode
![err](https://user-images.githubusercontent.com/27343530/116232163-fabf1500-a76e-11eb-864c-66a066b10d62.png)

**Comment by ccoreilly** [comment]
Models are downloaded in the background by the web worker. Can you provide more information?
- how do you start the demo locally?
- what Firefox version are you using?
- can you share the output of the browser console?
