### ISSUE TITLE
recognizer.on result never gets called.

### ISSUE THREAD

**Issue by tab-zero** [ccoreilly/vosk-browser#30]
I used the react code, and it never calls this piece of code.  Is there a parameter to set to enable collecting result?

```
recognizer.on("result", (message: any) => {
      const { result } = message;
      setUtterances((utt: VoskResult[]) => [...utt, result]);
    });
```

**Comment by ccoreilly** [comment]
Are you sure the model is being loaded and audio is being sent? Please share more logs as results should be sent as long as enough audio is being sent to the worker.

**Comment by ccoreilly** [comment]
@tab-zero Can you share a reproduction script?

**Comment by ccoreilly** [comment]
Feel free to reopen if you can share a reproduction script.
