### ISSUE TITLE
vosk-browser/tree/master/examples/modern-vanilla

### ISSUE THREAD

**Issue by emersonium** [ccoreilly/vosk-browser#33]
Hi Ciaran, great work, the web demo is very impressive !

Is the tar.gz the correct file format that this library expects ? I can not get the basic demo above to load,  or does it need something else, like an extracted version of the language library? 

Spent hours trying to figure out what is wrong,  it seems to have issues loading the library. 

this is the error I get when trying to run it in Chrome  (also tried Opera and Firefox)
""""
cb15bbf8-7209-4922-9c12-0b9e258dbd24:127 Error: HTTP error! status: 404
    at cb15bbf8-7209-4922-9c12-0b9e258dbd24:41:4212557
    at Generator.next (<anonymous>)
    at loop (cb15bbf8-7209-4922-9c12-0b9e258dbd24:41:4211624)
    at cb15bbf8-7209-4922-9c12-0b9e258dbd24:41:4211805
"""

the directory I run it in (linux webserver running apache)  has this file (english):
     **vosk-model-small-en-us-0.15.tar.gz**

and I updated the index.js demo to call it:
from:
    const model = await Vosk.createModel('model.tar.gz');
to 
    **const model = await Vosk.createModel('vosk-model-small-en-us-0.15.tar.gz');**

I am  really excited about getting this to work, so would really appreciate  your  help with any basic demo anyone could run locally.

**thanks!**
Emerson

**Comment by ccoreilly** [comment]
Hi Emerson,

tar.gz is the correct format but it seems it cannot download the model from your server. The library just adds what you pass the createModel method to the current location. Can you double check the model is downloadable?

**Comment by emersonium** [comment]
thank you Ciaran, you are correct. The model was downloadable, but it seems only a hard link works, for some reason relative link did not work.

thanks again!
Emerson
