### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by raghavendrajain** [ccoreilly/vosk-browser#35]
Hi,

Thanks for this work. I am using Chrome. The model file model.tar.gz is placed in the same folder. It never moves past "Loading..." message!

**how do you start the demo locally?**

Navigated to `modern-vanilla` directory and launched `python3 -m http.server`

**can you share the output of the browser console?**

ERROR (VoskAPI:Model():src/model.cc:122) Folder '/vosk/model_tar_gz' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
put_char @ 82049aad-16de-4cf3-9fcf-0c277f01fe02:41

**Comment by ccoreilly** [comment]
Do you have a model in the `modern-vanilla` folder?

**Comment by raghavendrajain** [comment]
Yes @ccoreilly

**Comment by ccoreilly** [comment]
It looks like it either is empty or does not follow the expected structure. Can you share it?

**Comment by raghavendrajain** [comment]
├── index.css
├── index.html
├── index.js
├── model.tar.gz
├── recognizer-processor.js
├── vosk.js
├── vosk-model-small-en-us-0.15
│   ├── am
│   │   └── final.mdl
│   ├── conf
│   │   ├── mfcc.conf
│   │   └── model.conf
│   ├── graph
│   │   ├── disambig_tid.int
│   │   ├── Gr.fst
│   │   ├── HCLr.fst
│   │   └── phones
│   │       └── word_boundary.int
│   ├── ivector
│   │   ├── final.dubm
│   │   ├── final.ie
│   │   ├── final.mat
│   │   ├── global_cmvn.stats
│   │   ├── online_cmvn.conf

**Comment by ccoreilly** [comment]
The same model is already packaged in the react example under `public/models`

**Comment by raghavendrajain** [comment]
Crap! Understood. The output of `tar -ztvf model.tar.gz` is  `vosk-model-small-en-us-0.15`

**Comment by raghavendrajain** [comment]
> The same model is already packaged in the react example under `public/models`

OK. I will check it there. I intend to basically use the Japanese language and its word-timestamp feature, so I'd need to package my own.
