### ISSUE TITLE
How can I add a new language?

### ISSUE THREAD

**Issue by Nata0801** [ccoreilly/vosk-browser#42]
I have downloaded a Ukrainian model and changed archive type to tar.gz, but I couldn't load it in the browser. I have looked into other archives but noticed they have a file of unknown type corresponding to each folder in archive. Is there a way to add a new language?
Thank you.

**Comment by ccoreilly** [comment]
You can use any vosk model, you just need to set the path correctly when calling createModel. The model files should be in a gzipped tar archive. Can you share what error you get in the console?

**Comment by 3NdR1m** [comment]
You don't have to convert your archive to tar.gz, [Vosk's zip archives](https://alphacephei.com/vosk/models) works fine.

**Comment by ccoreilly** [comment]
That is true, thank you for correcting me @3NdR1m

@Nata0801 please reopen with specific errors from the console
