### ISSUE TITLE
How to reduce delay between results?

### ISSUE THREAD

**Issue by 3NdR1m** [ccoreilly/vosk-browser#43]
Hi, I’ve noticed Vosk wait a few split seconds after the user is done talking before emitting a result, unlike partial results which get fired continuously, but aren’t as reliable. Since our application only respond to short, single-word commands, we’d like to reduce Vosk’s result “de-bounce” time to make our application feels more responsive. Do you have any suggestions?

**Comment by ccoreilly** [comment]
Hi @3NdR1m !
You can edit the endpoint rules in `model.conf` of the model you are using, to define when online decoding should stop (i.e. a final result should be sent). [Here](https://github.com/kaldi-asr/kaldi/blob/e1dd07b13c7f14c4f8f5532a281a044819e838c0/src/online2/online-endpoint.h#L46) is the reference.

**Comment by 3NdR1m** [comment]
Setting `--endpoint.rule1.min-trailing-silence=` through `--endpoint.rule4.min-trailing-silence=` seems to works. Thanks for your time.

**Comment by actor10** [comment]
> Setting `--endpoint.rule1.min-trailing-silence=` through `--endpoint.rule4.min-trailing-silence=` seems to works. Thanks for your time.

What values did you use?  (My program uses commands of just a word or two.). Henry
