### ISSUE TITLE
Is it possible to extract text from a large file faster than playback?

### ISSUE THREAD

**Issue by jwalton922** [ccoreilly/vosk-browser#47]
This is an awesome project. I was wondering if it was possible to extract the text from a file in a time shorter than the duration of the file? When testing out the hosted demo, it appears the text is extracted about the rate as if it were from a live source.

There's so much that is new and unfamiliar to me that I'm having a hard time understanding the code. I created a gist that has my attempt to make it work. [This is a gist of the beforeUpload function on the Upload component](https://gist.github.com/jwalton922/01dfe2ca893af27015dd64ff1d570d95)...it extracts text, but I can't quite tell if it's any faster.

Assuming the extraction can be done faster, any idea on how to get an approximate timestamp in the audio file?

**Comment by ccoreilly** [comment]
Inference time will depend on the CPU it is running. Vosk (the main engine this browser port is based on) can do transcription faster than real-time, especially if you use a GPU. I am not sure what your use-case is but maybe check the python examples in.the vosk repository.
