### ISSUE TITLE
keyword spotting mode

### ISSUE THREAD

**Issue by waterLover** [ccoreilly/vosk-browser#5]
Does it support keyword spotting mode，i really need this...

**Comment by ccoreilly** [comment]
Vosk does not support keyword spotting yet so neither does vosk-browser. You could achieve something similar with a custom model with a grammar of one word but it is not what it was designed for. There are many wakeword engines such as snowboy or precise but if you need one that works offline on the browser there is nothing that I know. You could try cross-compiling snowboy to WASM...
