### ISSUE TITLE
Vosk model

### ISSUE THREAD

**Issue by temitopefunmi** [ccoreilly/vosk-browser#50]
I am new to javascript. I want to see how the vosk-browser script worked using the sample script.
I downloaded a vosk model, zipped it as tar.gz and put it in the same folder as the script. I tried to just check for errors using a button onclick event on a html page. I got this on visual studio code:
Setting up persistent storage at /vosk null/4ccd8af6-9ac1-407c-9f6a-436d83146d69:147
File system synced from host to runtime null/4ccd8af6-9ac1-407c-9f6a-436d83146d69:40
Am I to create a folder named "vosk". I really do not understand.
Thank you for responding.

**Comment by arbdevml** [comment]
Hello, Temitopefunmi.

local development environment:
https://github.com/cytopia/devilbox

example:
https://github.com/ccoreilly/vosk-browser/tree/master/examples/modern-vanilla

update index.js:
https://github.com/ccoreilly/vosk-browser/blob/master/examples/modern-vanilla/index.js
const model = await Vosk.createModel('model.tar.gz');
model.tar.gz - replace to the model name from:
https://github.com/ccoreilly/vosk-browser/tree/master/examples/react/public/models

**Comment by temitopefunmi** [comment]
Thank you so much for responding.
I still get this error: _TypeError: Failed to construct 'URL': Invalid base URL__

**Comment by arbdevml** [comment]
Describe step by step your action.

**Comment by temitopefunmi** [comment]
Ok. I have this folder named modern_vanilla.
Inside the folder is: index.css, index.js, index.html, recognizer-processor.js, vosk.js and the model targzipped folder i downloaded from the public/react folder. I also renamed the model folder in the index.js.
I am using visual studio code on windows 10 system and debugging with google chrome on there.
Starting debugging opens the browser. 
Clicking on Start recognition, I see "Loading..." and that error in the debug console.

**Comment by arbdevml** [comment]
First of all, install nodejs and git if you haven't installed
https://nodejs.org/en/download/
https://git-scm.com/download/

1) npm i -g http-server
2) git clone --recursive https://github.com/ccoreilly/vosk-browser
3) cd vosk-browser/examples/
4) cp -r react/public/models/* modern-vanilla/
5) cd modern-vanilla/
6) cp vosk-model-small-en-us-0.15.tar.gz model.tar.gz
7) http-server -p 4200
8) Don't do any changes to the code.
Go to the browser and open the page:
http://127.0.0.1:4200/index.html
9) Press on the button "Start recognition" and wait few seconds
10) Appeared window "http://127.0.0.1:4200 wants to use your microphone"
Press Allow

Say: "Hello"

**Comment by temitopefunmi** [comment]
Thank you so much.
