### ISSUE TITLE
Result event not triggered on file upload

### ISSUE THREAD

**Issue by Clement-mim** [ccoreilly/vosk-browser#54]
Hello, I am working on a way to pass audio file to the recognizer all at once.

I took the react example and edited file-upload.tsx to send the whole file as buffer to the AudioStreamer "_write" method.
The problem reside on the "result" event of the recognizer not being fired after the process.
The "partialresult" event is called with every words but misses timestamps.

Here is the implementation of the "onChange" function in file-upload.tsx:

```
const onChange = useCallback(
    async ({ file }: UploadChangeParam<UploadFile<any>>) => {

      if (
        recognizer &&
        file.originFileObj &&
        file.percent === 100
      ) {
        const fileUrl = URL.createObjectURL(file.originFileObj);
        const _audioContext = audioContext ?? new AudioContext();
        const arr = await fetch(fileUrl).then((res) => res.arrayBuffer());

        _audioContext.decodeAudioData(arr, (buffer) => {
          let audioStreamer = new AudioStreamer(recognizer);
          audioStreamer._write(buffer, {
            objectMode: true,
          }, () => {
            console.log('done')
          });
        });
      }
    },
    [audioContext, recognizer]
  );
```
I have also noticed when uploading a second file it works well, the result event is triggered and includes both files data.

What I am missing? Is there a way to dispatch a "result" event?

**Comment by erikh2000** [comment]
This might be more of a workaround than directly addressing what you see, but...

You don't need `AudioStreamer` for your use case. You can call `AcceptWaveForm()` directly, and probably just once with a single `AudioBuffer`.

(unofficial response--I'm not the maintainer or involved with the project)

**Comment by Clement-mim** [comment]
Thanks for the fast reply! Indeed AudioStreamer is not usefull in my case. I can replace the function in decodeAudioData to just `recognizer.acceptWaveform(buffer)`

Unfortunately the error persist: `partialresult` is fired without `result`.
I also noticed something weird: by duplicating the line `recognizer.acceptWaveform(buffer)` the second call end by triggering `result` event (with both audios data).

This is what I have now:

```
_audioContext.decodeAudioData(arr, (buffer) => {
    recognizer.acceptWaveform(buffer);
    // Duplicate line to get results:
    recognizer.acceptWaveform(buffer);
});
```

**Comment by Clement-mim** [comment]
Hello, I have just created a PR with a new function "sendResult" that trigger the "result" event.

In my code I use it in the "partialresult" callback function (in recognizer.tsx) since I only have one buffer: the whole file.

It looks like this:

```
fileRecog.on("partialresult", (message: any) => {
    setPartial(message.result.partial);
    fileRecog.sendResults();
});
```
