### ISSUE TITLE
Malayalam Model is not loading 

### ISSUE THREAD

**Issue by fuhadabdulla** [ccoreilly/vosk-browser#70]
Malayalam Model is not loading , can you please fix it .

**Comment by erikh2000** [comment]
Could you give more details about what you are seeing? Also, do other language models load?

**Comment by fuhadabdulla** [comment]
I tried to load Malayalam model and English India model , both is not
loading . Only Default English Model is working .

When i load other models it is showing loading for a long time and is stuck
with loading button.

**Comment by lheine10** [comment]
I also have strange loading problems on Chrome Macbook Pro M1 with the english model.

Normal load time is 7secs, but maybe every third time the loading time is significant slower, like 35secs
or 59secs. This can happen after a fresh chrome restart or after a javascript reload on the same page.

It's completely random...

**Comment by lheine10** [comment]
Sometimes it fails after 60secs and this "Failed to sync file system" is shown in the console.log.
Maybe the emscripten file system has sync problems loading such a big model file...

<img width="828" alt="image" src="https://user-images.githubusercontent.com/118618714/222634480-83bcdb82-e490-40f8-ad94-d07ec5c10c67.png">

**Comment by lheine10** [comment]
I figured out my problem:
I was loading the model as a blobUrl.

The blob url changes every time and confuses the emscripten cached files in the indexDb.

The files in the indexDb are stored with filenames that are prefixed with the model url...

**Comment by fuhadabdulla** [comment]
I am getting this error when loading malayalam model 

Error: HTTP error! status: 404
    download blob:https://ccoreilly.github.io/8a5ff3a2-2862-4175-b0d1-4929a4dea1d5:41
    loop blob:https://ccoreilly.github.io/8a5ff3a2-2862-4175-b0d1-4929a4dea1d5:41
    loop blob:https://ccoreilly.github.io/8a5ff3a2-2862-4175-b0d1-4929a4dea1d5:41
[8a5ff3a2-2862-4175-b0d1-4929a4dea1d5:117:21](blob:https://ccoreilly.github.io/8a5ff3a2-2862-4175-b0d1-4929a4dea1d5)
TypeError: result is undefined

**Comment by kavyamanohar** [comment]
@ccoreilly Can you please look into this?

**Comment by erikh2000** [comment]
Let's remember that this vosk-browser is free open source and that Ciaran isn't paid to update it or fix bugs. It would be a shame to demoralize the maintainer by poking at him.

The ideal response to this thread is a pull request with a fix. Some troubleshooting that narrows the bug to a specific cause would be pretty solid too. Everyone in the thread is a developer.

**Comment by kavyamanohar** [comment]
I was tracking down the root cause, and since it was Ciaran who helped me add the model, I thought a mention would bring this issue to attention.

My sincere apologies for the mention. I want to make it clear that I didn't mean to make Ciaran personally responsible and I regret any misunderstanding that may have caused. @erikh2000, Thanks for pointing this out.

**Comment by ccoreilly** [comment]
Sorry for the absence, I will try to have a look tonight!

**Comment by ccoreilly** [comment]
Solved in #71
